### ISSUE TITLE
Benchmark:  add CycloneDX-python

### ISSUE THREAD

**Issue by jkowalleck** [psf/sboms-for-python-packages#9]
add the following tool to the benchmarks: 

github: https://github.com/CycloneDX/cyclonedx-python
pypi: https://pypi.org/project/cyclonedx-bom/
docs: https://cyclonedx-bom-tool.readthedocs.io/
example for 
* venv: `cyclonedx-py environment --of JSON --sv 1.6 -o sbom.cdx.json --PEP-639 --gather-license-texts --pyproject my-pyproject.toml venv`
* requirements file: `cyclonedx-py requirements --of JSON --sv 1.6 -o sbom.cdx.json --pyproject my-pyproject.toml requirements.txt`

**Comment by sethmlarson** [comment]
Thanks, could you submit a pull request adding the new scripts?
